/*
----------------------------------------------------------------
Magnitude Analysis
----------------------------------------------------------------
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.
----------------------------------------------------------------
*/

-- Total customers by countries
SELECT
	country,
	COUNT (customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Total customers by gender
SELECT  
	gender,
	COUNT (customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Total products by category
SELECT 
	category,
	COUNT (product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- Average costs in each category
SELECT 
	category,
	AVG (cost) AS average_cost
FROM gold.dim_products
GROUP BY category
ORDER BY average_cost DESC;

-- Total revenue generated for each category
SELECT 
	p.category,
	SUM (s.sales_amount) AS revenue
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_products AS p
ON s.product_key = p.product_key
GROUP BY p.category
ORDER BY revenue DESC;

-- Total revenue generated by each customer
SELECT 
	c.customer_id,
	c.first_name,
	c.last_name,
SUM (s.sales_amount) AS total_revenue
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_customers AS c
ON s.customer_key = c.customer_key
GROUP BY
	c.customer_id,
	c.first_name,
	c.last_name
ORDER BY total_revenue DESC;

-- Distribution of sold items across countries
SELECT 
	c.country,
SUM (s.quantity) AS quantity
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_customers AS c
ON s.customer_key = c.customer_key
GROUP BY c.country
ORDER BY quantity DESC;
